# Generated by Django 4.0.5 on 2022-06-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwsl', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activites',
            name='title',
        ),
        migrations.AlterField(
            model_name='experience',
            name='clients',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='projects',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='years',
            field=models.IntegerField(),
        ),
    ]
