# Generated by Django 4.0.5 on 2022-06-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwsl', '0002_remove_activites_title_alter_experience_clients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activites',
            name='body',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='directors',
            name='img',
            field=models.ImageField(null=True, upload_to='pictures'),
        ),
        migrations.AlterField(
            model_name='directors',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='directors',
            name='position',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='clients',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='projects',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='skill',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='years',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='proffession',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
