# Generated by Django 4.0.5 on 2022-07-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwsl', '0003_alter_activites_body_alter_directors_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activites',
            name='title',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
